package com.android.billingclient.api;

abstract class s {
    static final d A;
    static final d B;
    static final d C;
    static final d D;
    static final d E;
    static final d F;
    static final d a;
    static final d b;
    static final d c;
    static final d d;
    static final d e;
    static final d f;
    static final d g;
    static final d h;
    static final d i;
    static final d j;
    static final d k;
    static final d l;
    static final d m;
    static final d n;
    static final d o;
    static final d p;
    static final d q;
    static final d r;
    static final d s;
    static final d t;
    static final d u;
    static final d v;
    static final d w;
    static final d x;
    static final d y;
    static final d z;

    static {
        a d$a0 = d.c();
        d$a0.c(3);
        d$a0.b("Google Play In-app Billing API version is less than 3");
        s.a = d$a0.a();
        a d$a1 = d.c();
        d$a1.c(3);
        d$a1.b("Google Play In-app Billing API version is less than 9");
        s.b = d$a1.a();
        a d$a2 = d.c();
        d$a2.c(3);
        d$a2.b("Billing service unavailable on device.");
        s.c = d$a2.a();
        a d$a3 = d.c();
        d$a3.c(5);
        d$a3.b("Client is already in the process of connecting to billing service.");
        s.d = d$a3.a();
        a d$a4 = d.c();
        d$a4.c(5);
        d$a4.b("The list of SKUs can\'t be empty.");
        s.e = d$a4.a();
        a d$a5 = d.c();
        d$a5.c(5);
        d$a5.b("SKU type can\'t be empty.");
        s.f = d$a5.a();
        a d$a6 = d.c();
        d$a6.c(5);
        d$a6.b("Product type can\'t be empty.");
        s.g = d$a6.a();
        a d$a7 = d.c();
        d$a7.c(-2);
        d$a7.b("Client does not support extra params.");
        s.h = d$a7.a();
        a d$a8 = d.c();
        d$a8.c(5);
        d$a8.b("Invalid purchase token.");
        s.i = d$a8.a();
        a d$a9 = d.c();
        d$a9.c(6);
        d$a9.b("An internal error occurred.");
        s.j = d$a9.a();
        a d$a10 = d.c();
        d$a10.c(5);
        d$a10.b("SKU can\'t be null.");
        s.k = d$a10.a();
        a d$a11 = d.c();
        d$a11.c(0);
        s.l = d$a11.a();
        a d$a12 = d.c();
        d$a12.c(-1);
        d$a12.b("Service connection is disconnected.");
        s.m = d$a12.a();
        a d$a13 = d.c();
        d$a13.c(2);
        d$a13.b("Timeout communicating with service.");
        s.n = d$a13.a();
        a d$a14 = d.c();
        d$a14.c(-2);
        d$a14.b("Client does not support subscriptions.");
        s.o = d$a14.a();
        a d$a15 = d.c();
        d$a15.c(-2);
        d$a15.b("Client does not support subscriptions update.");
        s.p = d$a15.a();
        a d$a16 = d.c();
        d$a16.c(-2);
        d$a16.b("Client does not support get purchase history.");
        s.q = d$a16.a();
        a d$a17 = d.c();
        d$a17.c(-2);
        d$a17.b("Client does not support price change confirmation.");
        s.r = d$a17.a();
        a d$a18 = d.c();
        d$a18.c(-2);
        d$a18.b("Play Store version installed does not support cross selling products.");
        s.s = d$a18.a();
        a d$a19 = d.c();
        d$a19.c(-2);
        d$a19.b("Client does not support multi-item purchases.");
        s.t = d$a19.a();
        a d$a20 = d.c();
        d$a20.c(-2);
        d$a20.b("Client does not support offer_id_token.");
        s.u = d$a20.a();
        a d$a21 = d.c();
        d$a21.c(-2);
        d$a21.b("Client does not support ProductDetails.");
        s.v = d$a21.a();
        a d$a22 = d.c();
        d$a22.c(-2);
        d$a22.b("Client does not support in-app messages.");
        s.w = d$a22.a();
        a d$a23 = d.c();
        d$a23.c(-2);
        d$a23.b("Client does not support user choice billing.");
        s.x = d$a23.a();
        a d$a24 = d.c();
        d$a24.c(-2);
        d$a24.b("Play Store version installed does not support external offer.");
        s.y = d$a24.a();
        a d$a25 = d.c();
        d$a25.c(5);
        d$a25.b("Unknown feature");
        s.z = d$a25.a();
        a d$a26 = d.c();
        d$a26.c(-2);
        d$a26.b("Play Store version installed does not support get billing config.");
        s.A = d$a26.a();
        a d$a27 = d.c();
        d$a27.c(-2);
        d$a27.b("Query product details with serialized docid is not supported.");
        s.B = d$a27.a();
        a d$a28 = d.c();
        d$a28.c(4);
        d$a28.b("Item is unavailable for purchase.");
        s.C = d$a28.a();
        a d$a29 = d.c();
        d$a29.c(-2);
        d$a29.b("Query product details with developer specified account is not supported.");
        s.D = d$a29.a();
        a d$a30 = d.c();
        d$a30.c(-2);
        d$a30.b("Play Store version installed does not support alternative billing only.");
        s.E = d$a30.a();
        a d$a31 = d.c();
        d$a31.c(5);
        d$a31.b("To use this API you must specify a PurchasesUpdateListener when initializing a BillingClient.");
        s.F = d$a31.a();
    }

    static d a(int v, String s) {
        a d$a0 = d.c();
        d$a0.c(v);
        d$a0.b(s);
        return d$a0.a();
    }
}

