package r1;

import android.os.Parcel;
import android.os.Parcelable.Creator;
import g1.o;
import h1.c;
import q1.r;

public final class f extends r {
    public static final Parcelable.Creator CREATOR;
    private final boolean e;
    private final boolean f;
    private final boolean g;
    private final boolean h;
    private final boolean i;
    private final boolean j;
    private final boolean k;
    private final boolean l;
    private final boolean m;
    private final boolean n;

    static {
        f.CREATOR = new g();
    }

    public f(boolean z, boolean z1, boolean z2, boolean z3, boolean z4, boolean z5, boolean z6, boolean z7, boolean z8, boolean z9) {
        this.e = z;
        this.f = z1;
        this.g = z2;
        this.h = z3;
        this.i = z4;
        this.j = z5;
        this.k = z6;
        this.l = z7;
        this.m = z8;
        this.n = z9;
    }

    @Override
    public final boolean equals(Object object0) {
        if(!(object0 instanceof f)) {
            return false;
        }
        return this == object0 ? true : this.e == ((f)object0).e && this.f == ((f)object0).f && this.g == ((f)object0).g && this.h == ((f)object0).h && this.i == ((f)object0).i && this.j == ((f)object0).j && this.k == ((f)object0).k && this.l == ((f)object0).l && this.m == ((f)object0).m && this.n == ((f)object0).n;
    }

    @Override
    public final int hashCode() {
        return o.b(new Object[]{Boolean.valueOf(this.e), Boolean.valueOf(this.f), Boolean.valueOf(this.g), Boolean.valueOf(this.h), Boolean.valueOf(this.i), Boolean.valueOf(this.j), Boolean.valueOf(this.k), Boolean.valueOf(this.l), Boolean.valueOf(this.m), Boolean.valueOf(this.n)});
    }

    @Override
    public final String toString() {
        return o.c(this).a("forbiddenToHavePlayerProfile", Boolean.valueOf(this.e)).a("requiresParentPermissionToShareData", Boolean.valueOf(this.f)).a("hasSettingsControlledByParent", Boolean.valueOf(this.g)).a("requiresParentPermissionToUsePlayTogether", Boolean.valueOf(this.h)).a("canUseOnlyAutoGeneratedGamerTag", Boolean.valueOf(this.i)).a("forbiddenToRecordVideo", Boolean.valueOf(this.j)).a("shouldSeeEquallyWeightedButtonsInConsents", Boolean.valueOf(this.k)).a("requiresParentConsentToUseAutoSignIn", Boolean.valueOf(this.l)).a("shouldSeeSimplifiedConsentMessages", Boolean.valueOf(this.m)).a("forbiddenToUseProfilelessRecall", Boolean.valueOf(this.n)).toString();
    }

    @Override  // android.os.Parcelable
    public final void writeToParcel(Parcel parcel0, int v) {
        int v1 = c.a(parcel0);
        c.c(parcel0, 1, this.e);
        c.c(parcel0, 2, this.f);
        c.c(parcel0, 3, this.g);
        c.c(parcel0, 4, this.h);
        c.c(parcel0, 5, this.i);
        c.c(parcel0, 6, this.j);
        c.c(parcel0, 7, this.k);
        c.c(parcel0, 8, this.l);
        c.c(parcel0, 9, this.m);
        c.c(parcel0, 10, this.n);
        c.b(parcel0, v1);
    }
}

